package com.briup.kfc.bean;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_order.id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_order.order_time
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    private String orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_order.status
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_order.user_id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_order.id
     *
     * @return the value of kfc_order.id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_order.id
     *
     * @param id the value for kfc_order.id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_order.order_time
     *
     * @return the value of kfc_order.order_time
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_order.order_time
     *
     * @param orderTime the value for kfc_order.order_time
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime == null ? null : orderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_order.status
     *
     * @return the value of kfc_order.status
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_order.status
     *
     * @param status the value for kfc_order.status
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_order.user_id
     *
     * @return the value of kfc_order.user_id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_order.user_id
     *
     * @param userId the value for kfc_order.user_id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}