package com.briup.kfc.bean;

public class OrderOnline {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_orderline.id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_orderline.num
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    private Long num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_orderline.order_id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_orderline.product_id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    private Long productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_orderline.id
     *
     * @return the value of kfc_orderline.id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_orderline.id
     *
     * @param id the value for kfc_orderline.id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_orderline.num
     *
     * @return the value of kfc_orderline.num
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_orderline.num
     *
     * @param num the value for kfc_orderline.num
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public void setNum(Long num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_orderline.order_id
     *
     * @return the value of kfc_orderline.order_id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_orderline.order_id
     *
     * @param orderId the value for kfc_orderline.order_id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_orderline.product_id
     *
     * @return the value of kfc_orderline.product_id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_orderline.product_id
     *
     * @param productId the value for kfc_orderline.product_id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }
}