package com.briup.kfc.bean;

import java.math.BigDecimal;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_product.id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_product.name
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_product.description
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_product.price
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_product.photo
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_product.status
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_product.xiaoliang
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    private Long xiaoliang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kfc_product.category_id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    private Long categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_product.id
     *
     * @return the value of kfc_product.id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_product.id
     *
     * @param id the value for kfc_product.id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_product.name
     *
     * @return the value of kfc_product.name
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_product.name
     *
     * @param name the value for kfc_product.name
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_product.description
     *
     * @return the value of kfc_product.description
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_product.description
     *
     * @param description the value for kfc_product.description
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_product.price
     *
     * @return the value of kfc_product.price
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_product.price
     *
     * @param price the value for kfc_product.price
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_product.photo
     *
     * @return the value of kfc_product.photo
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_product.photo
     *
     * @param photo the value for kfc_product.photo
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_product.status
     *
     * @return the value of kfc_product.status
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_product.status
     *
     * @param status the value for kfc_product.status
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_product.xiaoliang
     *
     * @return the value of kfc_product.xiaoliang
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public Long getXiaoliang() {
        return xiaoliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_product.xiaoliang
     *
     * @param xiaoliang the value for kfc_product.xiaoliang
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public void setXiaoliang(Long xiaoliang) {
        this.xiaoliang = xiaoliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kfc_product.category_id
     *
     * @return the value of kfc_product.category_id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kfc_product.category_id
     *
     * @param categoryId the value for kfc_product.category_id
     *
     * @mbg.generated Sun May 19 23:28:11 CST 2019
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }
}